### ISSUE TITLE
使用 Scoop 安装测试版的本体却安装了稳定版的插件导致识别不到插件一例

### ISSUE THREAD

**Issue by fangxingweiai** [Qv2ray/mochi#1]
![image](https://user-images.githubusercontent.com/62201630/100073758-de921180-2e78-11eb-8bcc-d69cba73ca42.png)

**Comment by DuckSoft** [comment]
Assigned to @kidonng.

**Comment by kidonng** [comment]
安装 `qv2ray-plugin-ssr-beta` 而不是 `qv2ray-plugin-ssr`。

https://qv2ray.net/plugins/usage.html#qv2ray-%E6%B2%A1%E6%9C%89%E6%A3%80%E6%B5%8B%E5%88%B0%E6%8F%92%E4%BB%B6

![image](https://user-images.githubusercontent.com/44045911/100076757-865d0e80-2e7c-11eb-9dcd-55e2dd6df6bd.png)
