### ISSUE TITLE
scoop下载不了qv2ray-plugin-trojan-go-beta，发生了甚么事？

### ISSUE THREAD

**Issue by fangxingweiai** [Qv2ray/mochi#2]
![image](https://user-images.githubusercontent.com/62201630/100098040-69363900-2e98-11eb-85b3-1a01f121802d.png)

**Comment by MarksonHon** [comment]
@gankang 仔细阅读Mochi软件源的文档， ~~它的部分包依赖于sushi源的一些组件。~~ 已修正

**Comment by kidonng** [comment]
c8e626250f8ce6e9dea05a29f214dcf6205c6eac
