### ISSUE TITLE
能否添加xray？

### ISSUE THREAD

**Issue by weihao306** [Qv2ray/mochi#3]
[v2ray](https://github.com/v2fly/v2ray-core/releases)在4.33.0版本后移除了xtls，之后xtls的作者自建了新的分支[xray](https://github.com/XTLS/Xray-core)以支持xtls，希望能加上xray的下载

**Comment by kidonng** [comment]
~~We are working on optimizing auto update process~~ Gugugu, Please use https://github.com/kidonng/sushi for the time being.
